version: '3.8'

services:
  fmtv-downloader:
    build: .
    container_name: fmtv-downloader-container
    environment:
      - LASTFM_API_KEY=your_lastfm_api_key
      - LASTFM_USERNAME=your_lastfm_username
      - DOWNLOAD_PATH=/downloads
      - APP_DATA_PATH=/appdata
      - POLLING_INTERVAL=300  # Adjust as needed
      - START_TIMESTAMP=1624147200  # Example start timestamp (replace with your desired value)

    volumes:
      - ./downloads:/downloads  # Directory for downloaded files
      - ./appdata:/appdata  # Directory for app data (logs, etc.)
